# Generated by Django 5.2.5 on 2025-08-12 07:09

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="blog.category",
                        verbose_name="父级",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, verbose_name="SEO 标题"),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=500, verbose_name="SEO 描述"),
                ),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("body_markdown", models.TextField(verbose_name="正文 Markdown")),
                ("body_html", models.TextField(blank=True, verbose_name="正文 HTML")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="covers/", verbose_name="封面图"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("scheduled", "计划发布"),
                            ("published", "已发布"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                ("is_featured", models.BooleanField(default=False, verbose_name="置顶/推荐")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="浏览量")),
                (
                    "reading_time",
                    models.PositiveIntegerField(default=1, verbose_name="阅读时长(分钟)"),
                ),
                ("allow_comment", models.BooleanField(default=True, verbose_name="允许评论")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("nickname", models.CharField(blank=True, max_length=50, verbose_name="昵称")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="邮箱")),
                ("content", models.TextField(verbose_name="内容")),
                ("is_approved", models.BooleanField(default=False, verbose_name="已审核")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("ua", models.CharField(blank=True, max_length=255, verbose_name="UA")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.comment",
                        verbose_name="父评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "published_at"], name="blog_post_status_5b2843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="blog_post_slug_cdb902_idx"),
        ),
    ]
