# Generated by Django 5.2.5 on 2025-08-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="version",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="版本"),
        ),
        migrations.AddField(
            model_name="comment",
            name="version",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="版本"),
        ),
        migrations.AddField(
            model_name="post",
            name="version",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="版本"),
        ),
    ]
