# Generated by Django 5.2.5 on 2025-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_category_version_comment_version_post_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, verbose_name="摘要"),
        ),
    ]
