# Generated by Django 5.2.5 on 2025-08-12 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_excerpt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="category",
            table_comment="文章分类",
        ),
        migrations.AlterModelTableComment(
            name="comment",
            table_comment="文章评论",
        ),
        migrations.AlterModelTableComment(
            name="post",
            table_comment="文章",
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, db_comment="分类描述", verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_comment="分类名称（唯一）", max_length=100, unique=True, verbose_name="分类名称"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_comment="父级分类（可为空）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="blog.category",
                verbose_name="父级",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                db_comment="唯一标识 Slug", max_length=255, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="version",
            field=models.PositiveSmallIntegerField(
                db_comment="版本号（随保存自增）", default=1, verbose_name="版本"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(db_comment="评论内容", verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(
                blank=True, db_comment="访客邮箱", max_length=254, verbose_name="邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, db_comment="评论 IP 地址", null=True, verbose_name="IP"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(
                db_comment="是否已审核", default=False, verbose_name="已审核"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="nickname",
            field=models.CharField(
                blank=True, db_comment="访客昵称", max_length=50, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_comment="父评论（可为空）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog.comment",
                verbose_name="父评论",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                db_comment="所属文章",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
                verbose_name="文章",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="ua",
            field=models.CharField(
                blank=True, db_comment="用户代理 UA", max_length=255, verbose_name="UA"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_comment="评论用户（可为空）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="version",
            field=models.PositiveSmallIntegerField(
                db_comment="版本号（随保存自增）", default=1, verbose_name="版本"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="allow_comment",
            field=models.BooleanField(
                db_comment="是否允许评论", default=True, verbose_name="允许评论"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                db_comment="作者",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body_html",
            field=models.TextField(
                blank=True, db_comment="渲染后的 HTML 正文", verbose_name="正文 HTML"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body_markdown",
            field=models.TextField(db_comment="Markdown 正文", verbose_name="正文 Markdown"),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_comment="所属分类（可为空）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.category",
                verbose_name="分类",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                db_comment="封面图片",
                null=True,
                upload_to="covers/",
                verbose_name="封面图",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, db_comment="文章摘要", verbose_name="摘要"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                db_comment="是否置顶/推荐", default=False, verbose_name="置顶/推荐"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True, db_comment="SEO 描述", max_length=500, verbose_name="SEO 描述"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_title",
            field=models.CharField(
                blank=True, db_comment="SEO 标题", max_length=255, verbose_name="SEO 标题"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True, db_comment="发布时间", null=True, verbose_name="发布时间"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="reading_time",
            field=models.PositiveIntegerField(
                db_comment="预计阅读时长（分钟）", default=1, verbose_name="阅读时长(分钟)"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                db_comment="唯一标识 Slug", max_length=255, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "草稿"), ("scheduled", "计划发布"), ("published", "已发布")],
                db_comment="发布状态",
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(db_comment="文章标题", max_length=200, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="version",
            field=models.PositiveSmallIntegerField(
                db_comment="版本号（随保存自增）", default=1, verbose_name="版本"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(
                db_comment="浏览次数", default=0, verbose_name="浏览量"
            ),
        ),
    ]
