# Generated by Django 5.2.5 on 2025-08-12 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="profile",
            table_comment="用户个人资料",
        ),
        migrations.AlterModelTableComment(
            name="user",
            table_comment="用户表",
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, db_comment="头像", null=True, upload_to="avatars/", verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, db_comment="个人简介", verbose_name="简介"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(
                blank=True, db_comment="昵称", max_length=50, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                db_comment="关联用户",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, db_comment="个人网站", verbose_name="个人网址"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                db_comment="加入时间", default=django.utils.timezone.now, verbose_name="加入时间"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_comment="邮箱地址（唯一）",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                db_comment="邮箱是否已验证", default=False, verbose_name="邮箱已验证"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, db_comment="名", max_length=150, verbose_name="名"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                db_comment="是否为活动用户",
                default=True,
                help_text="指定用户是否应被视为活动状态。取消选择而不是删除账户。",
                verbose_name="激活",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                db_comment="是否可登录管理站点",
                default=False,
                help_text="指定用户是否可以登录到此管理站点。",
                verbose_name="工作人员状态",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, db_comment="姓", max_length=150, verbose_name="姓"),
        ),
    ]
